### ISSUE TITLE
About args and NNI

### ISSUE THREAD

**Issue by ENDLICHERE** [yongcaoplus/TIN-SLT#1]
I download the processed data and pre-trained model of bert and modify the corresponding path in automl and trainer.  But there is no trial metric on nni web.

Then I try to train the model without nni, use `python trainer/train_pipeline dataset/processed/stmc_add_text_to_gloss_0.9/`.  

It raises" AssertError: Must specify batch size either with --max-tokens or --max-sentences", after added default values, it raises "TypeError:__init__() missing 3 required positional arguments: 'bertencoder', 'berttokenizer', and 'mask_cls_sep'".

I wonder how to set the args without NNI and how to train the model correctly with NNI.

**Comment by yongcaoplus** [comment]
I fixed this bug. Please try it again.
And I add the choice to train with or without  NNI, so please refer to our new readme.md for a detailed training tutorial.

**Comment by ENDLICHERE** [comment]
Thank you very much. I can train the model without automl successfully now, but there is still something wrong with automl. 
I install nni==2.3 to match the version of fairseq (0.6.2) and only change the corresponding path in config.yml.
It raises "ERROR: Config V1 validation failed: SchemaError('builtinTunerName should be in range of ()!')" when using `nnictl create --config automl/config.yml -p 11111`.

**Comment by yongcaoplus** [comment]
I think this is the nni package bug and didn't happened to my platform.
It seems you didn't install the correct version of NNI or didn't config Tuner parameter correctly. If you succeed in the above steps, the logs will remind you to choose a specific tuner such as 'TPE', 'Random', 'Anneal', 'Evolution', 'BatchTuner', etc. 
Perhaps you can reinstall nni or check the config of tuner.

If it is still not solved, please raise an issue here: [https://github.com/microsoft/nni/issues](https://github.com/microsoft/nni/issues).
